### ISSUE TITLE
Update Website Title to ArtiGenius-AI

### ISSUE THREAD

**Issue by ayuugoyal** [SDC-USAR/ArtiGenius-AI#17]
## Bug Report 🐛

**Description:**

- Update the website's homepage title from "Image Generation AI" to "ArtiGenius-AI."
- Verify and test the changes to ensure they reflect accurately across all web browsers and devices.

**Issue Details:**

- Current Website Title: Image Generation AI
- Proposed Website Title: ArtiGenius-AI

**Screenshots (if applicable):**

If relevant, add screenshots or error messages.

**Additional Information:**

- Operating System: [e.g., Windows 11]
- Browser/Version: [e.g., Firefox 118.0.1]

## Checklist

- [ ] I have searched the issues to ensure this bug has not been reported before.
- [ ] I have provided all the requested information.

**Comment by monicknog** [comment]
Assign this issue to me

**Comment by ayuugoyal** [comment]
@monicknog go ahead

**Comment by ich-tanishqa** [comment]
assign this issue to  me.
