### ISSUE TITLE
Update Input field for dark mode

### ISSUE THREAD

**Issue by ayuugoyal** [SDC-USAR/ArtiGenius-AI#20]
## Bug Report 🐛

**Description:**

The input field remains unchanged in dark mode, lacking any improvements from its appearance in light mode. Enhancements are needed to optimize its visibility and usability in dark mode.

**Screenshots (if applicable):**

If relevant, add screenshots or error messages.

**Additional Information:**

- Operating System: [e.g., Windows 11]
- Browser/Version: [e.g., Firefox 118.0.1]

## Checklist

- [ ] I have searched the issues to ensure this bug has not been reported before.
- [ ] I have provided all the requested information.

**Comment by ftonato** [comment]
I'm on it!
