### ISSUE TITLE
Implement Dark and Light Mode Feature

### ISSUE THREAD

**Issue by ayuugoyal** [SDC-USAR/ArtiGenius-AI#4]
## Feature Request ✨

**Description:**

The goal of this issue is to implement a dark and light mode feature within our application, allowing users to switch between different color schemes based on their preferences.

**Solution:**

Dark and light modes have become a standard feature in many applications, enhancing usability and reducing eye strain, especially during low-light conditions. Introducing this feature would greatly improve the accessibility and user-friendliness of our application.

**Use Case:**

1. User Interface (UI): Implement changes to the UI elements such as background color, text color, and button styles to accommodate both dark and light modes.
2. Toggle Functionality: Add a toggle button or switch in the application settings that enables users to switch between dark and light modes seamlessly.
3. Consistency: Ensure consistency in design across all pages and elements in both modes, maintaining a coherent user experience.

## Checklist

- [x] I have searched the issues to ensure this feature request has not been submitted before.
- [x] I have provided all the necessary details for this feature request.

**Comment by Ajay-308** [comment]
Assign this issue to me

**Comment by ayuugoyal** [comment]
@Ajay-308 assigned this to you

**Comment by Ajay-308** [comment]
done

**Comment by Ajay-308** [comment]
Done this task 
PR #13
