### ISSUE TITLE
Create CONTRIBUTING.md 

### ISSUE THREAD

**Issue by shubhsardana29** [SDC-USAR/ArtiGenius-AI#5]
## Documentation Issue 📖

**Description:**

This file will serve as a guide for potential contributors to understand how they can contribute to the project effectively. 

**Proposed Change:**

It should provide a clear and structured guide for potential contributors, making it easier for them to get involved in the project.

**Motivation:**

Creating a CONTRIBUTING.md file is essential for the following reasons:

- It sets expectations and standards for code quality and collaboration, helping maintain a consistent codebase.
- It fosters a welcoming and inclusive community by outlining community guidelines and a code of conduct.

**Additional Information (if applicable):**

None at this time

**Comment by archit203** [comment]
please assign this to me.

**Comment by Vivek7038** [comment]
can i send a pr directly without being assigned a issue
