### ISSUE TITLE
Design a unique logo for the app

### ISSUE THREAD

**Issue by ayuugoyal** [SDC-USAR/ArtiGenius-AI#6]
## Custom Issue 🚀

**Description:**

The logo for the text-to-image generation app should capture the essence of transformation, creativity, and technology. Here's a unique concept for your app's logo.

1. Symbol: Combine a stylized letter "A" (representing text) with a pixelated brushstroke or digital pen nib. This fusion symbolizes the conversion of text into visual art.

2. Color Palette: Use vibrant and modern colors. Consider a gradient that starts with deep blue or purple representing the depth of text and transitions into lively shades of green or orange, representing creativity and innovation.

3. Typography: Choose a sleek and modern font for the app's name beneath the symbol. Make sure it's easily readable even in smaller sizes.

**Checklist (if applicable) ✅:**

- [ ] I have searched the issues to ensure a similar request or issue has not been submitted before.
- [ ] I have provided all the necessary details.

**Comment by exrol** [comment]
I made a logo following your suggestions, i hope you like it :-)

PR : https://github.com/SDC-USAR/ArtiGenius-AI/pull/8

**Comment by rohitdubey1352** [comment]
Hey, @Adi-ty Can I do this task? 
Please assign this task to me.

**Comment by Zeomite** [comment]
I have created a logo following your recommendations. I hope you find it appealing!

PR: #12

**Comment by Pratikdate** [comment]
Assign me i have good design experience

**Comment by priyankeshh** [comment]
I have designed some logos as well as modified the index.tsx file to use them on website.

You can find the pull request at https://github.com/SDC-USAR/ArtiGenius-AI/pull/22

**Comment by ayuugoyal** [comment]
@priyankeshh thank you for your contribution:)

**Comment by priyankeshh** [comment]
@ayuugoyal  you also need to change the favicon.ico in the public folder in order to change the browser icon

**Comment by ayuugoyal** [comment]
@priyankeshh yeahh i have done that... thanks again:)
